require("blentar.plugin_config.onedark")
require("blentar.plugin_config.lualine")
require("blentar.plugin_config.nvim-tree")
require("blentar.plugin_config.treesitter")
require("blentar.plugin_config.telescope")
