add_newline = false

[line_break]
disabled = true

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"
format = "$symbol "

[cmd_duration]
style = "bold yellow"

[directory]
style = "bold purple"

[git_branch]
style = "bold purple"

[git_status]
style = "bold orange"

[hostname]
style = "bold cyan"
disabled = false
ssh_only = false
format = "[$hostname]($style) ❯ "

[username]
format = " [$user]($style) "
style_user = "bold yellow"
disabled = false
show_always = true
